import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import SessionPro from "./components/SessionPro";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // let user =
  return (
    <html lang="en">
      <SessionPro>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased px-[9%] pb-20`}
        >
          <Navbar />
          {children}
        </body>
      </SessionPro>
    </html>
  );
}
